### ISSUE TITLE
NumberFormatException when running WDM on Hetzner

### ISSUE THREAD

**Issue by thatsIch** [bonigarcia/webdrivermanager#1160]
**Description of the problem**: 

We just migrated part of our CI/CD to Hetzner. Runnin a WDM-managed webdriver test throws a `NumberFormatException` on parsing `linux64`.

**Browser and version**: 

Chrome: 119

**Operating system and architecture**: 

Ubuntu 22.04 - 64 bit

**Selenium version**: 

Not sure which version it is.
We run it on Docker with this image

https://hub.docker.com/layers/selenium/standalone-chrome/119.0-20231102/images/sha256-9f57cf4eae1b0592c809443d0871d89653e389868f84c63620120fb333c86df7?context=explore

**WebDriverManager version**: 

Currently the latest version with 5.6.1

https://github.com/bonigarcia/webdrivermanager/releases/tag/webdrivermanager-5.6.1

through Maven

```xml
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.6.1</version>
            <scope>test</scope>
        </dependency>
```

**WebDriverManager call**: 
```
WebDriverManager.chromedriver().setup();

final var options = new ChromeOptions();
options.addArguments("--headless");
options.addArguments("start-maximized");
// to reduce interferences by installed extensions
options.addArguments("--disable-extensions");
// potential solution for random chrome crashing
// see https://stackoverflow.com/a/50642913
options.addArguments("--disable-dev-shm-usage");
options.addArguments("--no-sandbox");
options.addArguments("window-size=1920,1920");
// default headless webdrivers could accept the alert
// see https://stackoverflow.com/questions/26772793/org-openqa-selenium-unhandledalertexception-unexpected-alert-open
options.setCapability(CapabilityType.UNHANDLED_PROMPT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);

new ChromeDriver(options);
```

**WebDriverManager traces**: 

Omitted, but I can add it if this really helps in this case. Would be a significant overhead to activate the logging within the pipeline.

**Error log**: 
```
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "linux64"
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1429)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1194)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1445)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1426)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1194)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1419)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1194)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:426)
	at de.commodis.ui.common.webdriver.WebDriverTest.setupClass(WebDriverTest.java:29)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.NumberFormatException: For input string: "linux64"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:661)
	at java.base/java.lang.Integer.parseInt(Integer.java:777)
	at io.github.bonigarcia.wdm.online.Downloader.getTarget(Downloader.java:105)
	at io.github.bonigarcia.wdm.online.Downloader.download(Downloader.java:88)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1281)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1188)
	... 9 more
```

**Comment by bonigarcia** [comment]
I believe I found the root of the problem, and it should be fixed in the master branch.

@thatsIch You can try the new version bumping WebDriverManager to **5.6.2-SNAPSHOT**. This version (which contains the latest fix) is in the sonatype snapshots repositories. If using Maven, you also need to include the following in your pom.xml:

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

... or its equivalent in Gradle:

```
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
```

**Comment by thatsIch** [comment]
Thanks! I will give it a try

**Comment by thatsIch** [comment]
I can confirm - it works on Hetzner now! Thanks

**Comment by thatsIch** [comment]
Related problem - just wanted to link it

https://github.com/GoogleChromeLabs/chrome-for-testing/issues/60#issuecomment-1750084411

**Comment by thatsIch** [comment]
The reported problem was fixed with https://github.com/bonigarcia/webdrivermanager/commit/6299f0b131f0f8e3b0035d4022bcc94f48965730 and thus I close this issue.

**Comment by rohithkakumani** [comment]
> I am seeing the same issue , here is the log The webDriverManager version i have is implementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.6.3' Even tried 5.6.2 but its still the same
> 
> failing at my code statements below, tried both of them WebDriverManager.chromedriver().setup(); WebDriverManager.chromedriver().clearDriverCache().setup();
> 
> o.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"
> 
> ```
> at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
> at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
> at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1451)
> at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1432)
> at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
> at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1425)
> at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1195)
> at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
> at com.pandora.qa.oms.TestBase.beforeSuite(TestBase.java:45)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
> at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
> at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
> at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
> at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
> at org.testng.SuiteRunner.run(SuiteRunner.java:364)
> at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
> at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
> at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
> at org.testng.TestNG.runSuites(TestNG.java:1049)
> at org.testng.TestNG.run(TestNG.java:1017)
> at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
> at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
> ```
> 
> Caused by: java.lang.NumberFormatException: For input string: "public" at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.base/java.lang.Integer.parseInt(Integer.java:652) at java.base/java.lang.Integer.parseInt(Integer.java:770) at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:178) at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:155) at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1272) at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189) ... 26 more

Update your browser version. in POM.XML update webdrivermanager version to 5.6.4. Do project>> Clean and Project >>Build automatically. it should work..

**Comment by swatiradia** [comment]
@rohithkakumani  I seeing the same error as well. I did try to update browser and webdrivermanager version, and did a Clean Build. Still the same error.

[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver public (resolved driver for Chrome 122)
[main] INFO io.github.bonigarcia.wdm.cache.ResolutionCache - Clearing WebDriverManager resolution cache
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver public (For input string: "public") ... trying again avoiding reading release from repository
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver (latest version) (For input string: "public") ... trying again using latest driver stored in cache
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver public (resolved driver for Chrome 122)
[main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver public (For input string: "public")
java.lang.NumberFormatException: For input string: "public"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:178)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:155)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1282)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1199)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1461)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1442)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)

**Comment by mohanaravindvarma** [comment]
Yes even i am getting this issue in my azure pipelines. But not in my local machine.

java.lang.ExceptionInInitializerError
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"
Caused by: java.lang.NumberFormatException: For input string: "public"

**Comment by roypatel1** [comment]
not sure what changed on February 21/22, but since then also getting same error as above

io.cucumber.core.exception.CucumberException: Failed to instantiate class cucumberAutomation.stepDefinitions.StepDefinition_Homepage

	at io.cucumber.core.backend.DefaultObjectFactory.cacheNewInstance(DefaultObjectFactory.java:67)
	at io.cucumber.core.backend.DefaultObjectFactory.getInstance(DefaultObjectFactory.java:45)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:56)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:137)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:137)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.cucumber.core.backend.DefaultObjectFactory.cacheNewInstance(DefaultObjectFactory.java:53)
	... 42 more
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1445)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1461)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1442)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at ui.webDriverSetup.WebDriverConfig.startDriver(WebDriverConfig.java:37)

**Comment by anjaliSalesgent** [comment]
I also found same error 
io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"

	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1445)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1461)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1442)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at com.Salesgent.Base.base.setUp(base.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.NumberFormatException: For input string: "public"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:665)
	at java.base/java.lang.Integer.parseInt(Integer.java:781)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:178)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:155)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1282)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1199)
	... 36 more

**Comment by younessg** [comment]
I having the same issue, my project was working fine until I tried to run some tests today

**io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"**
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1445)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1461)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1442)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)


        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
        </dependency>

And <webdrivermanager.version>5.6.3</webdrivermanager.version>

The issue happens in my case when this code is called:

**WebDriverManager
            .chromedriver()
            .setup();**

**Comment by silverenio** [comment]
Got this all the same to all error on 5.6.3

Tried to update to 5.6.4 and received the same error:

io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"

**Comment by bonigarcia** [comment]
This is fixed in WebDriverManager 5.7.0. See #1226.

**Comment by nemethgabor83** [comment]
I'm still facing this issue with 5.7.0.

**Comment by anjaliSalesgent** [comment]
@silverenio & @younessg 

You don't need to be using the WebDriverManager anymore with Selenium 4. x.
Can you try removing it and working without it?

Selenium now can manage the web driver binary downloading, browser downloading itself, etc., via SeleniumManager. Selenium Manager by its behavior itself is very transparent to you and you wouldn’t even know that it exists.

Read more about it here: https://www.selenium.dev/documentation/selenium_manager/

**Comment by bonigarcia** [comment]
> Selenium now can manage the web driver binary downloading, browser downloading itself, etc., via SeleniumManager. Selenium Manager by its behavior itself is very transparent to you and you wouldn’t even know that it exists.

See more info about WebDriverManager and Selenium Manager here:

https://bonigarcia.dev/webdrivermanager/#webdrivermanager-and-selenium-manager

**Comment by Shafkat-ali** [comment]
Running into the same issue with selelnium version 3.141.59. Only chrome browser is having this issue. other browser manager works fine. I used latest version of the webdrivermanager 5.7.0, and still getting the same issue

```io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1414)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1430)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1408)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:426)
	at SeleniumDay5.TestingAlerts.setUp(TestingAlerts.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NumberFormatException: For input string: "public"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:177)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:154)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1262)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1183)
	... 32 more

```

**Comment by turepinar** [comment]
I was having same issue and tried to update/change many things. None of them worked. Then just realized that I IDE has an update on wait for last couple days. After I completed the IntelliJ update, things worked well suddenly.  At least worth to give it a try!

**Comment by nemethgabor83** [comment]
@turepinar Unfortunately it didn't solve the problem, but thanks for the hint.

**Comment by DarrenW-HMPPS** [comment]
Another "Me Too" message.  Running on Ubuntu in a Docker container and using FirefoxDriver with Firefox ESR version.  Not experienced these exceptions until upgrading to 5.7.0 yesterday.

java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getDriverVersionFromRepository(FirefoxDriverManager.java:140)
	at io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getLatestDriverVersionFromRepository(FirefoxDriverManager.java:115)
	at io.github.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(WebDriverManager.java:1248)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1154)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:426)
	at io.github.bonigarcia.wdm.WebDriverManager.create(WebDriverManager.java:431)
	at u.g.j.d.h.config.ComponentConfiguration.webDriver(ComponentConfiguration.kt:48)
	at u.g.j.d.h.config.ComponentConfiguration$$SpringCGLIB$$0.CGLIB$webDriver$2(<generated>)
	at u.g.j.d.h.config.ComponentConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at u.g.j.d.h.config.ComponentConfiguration$$SpringCGLIB$$0.webDriver(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:647)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:639)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:364)
	at org.springframework.web.context.request.AbstractRequestAttributesScope.get(AbstractRequestAttributesScope.java:45)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:361)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:200)
	at jdk.proxy3/jdk.proxy3.$Proxy138.navigate(Unknown Source)
	at u.g.j.d.h.p.AutomationClient.login(AutomationClient.kt:212)
	at u.g.j.d.h.p.AutomationClient.login$default(AutomationClient.kt:211)
	at u.g.j.d.h.p.AutomationClient.performLoggedInOperation(AutomationClient.kt:197)
	at u.g.j.d.h.p.AutomationClient.performLoggedInOperation$default(AutomationClient.kt:193)
	at u.g.j.d.h.p.AutomationClient.createOffender$suspendImpl(AutomationClient.kt:87)
	at u.g.j.d.h.p.AutomationClient.createOffender(AutomationClient.kt)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:207)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
	at org.springframework.core.CoroutinesUtils.lambda$invokeSuspendingFunction$3(CoroutinesUtils.java:137)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$4.invokeSuspend(IntrinsicsJvm.kt:270)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.reactor.MonoKt.monoInternal$lambda$2(Mono.kt:92)
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512)
	at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$DeferredResultSubscriber.connect(ReactiveTypeHandler.java:465)
	at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler.handleValue(ReactiveTypeHandler.java:163)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler.handleReturnValue(ResponseBodyEmitterReturnValueHandler.java:154)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)
	at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:145)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:225)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.servlet.v6_0.OpenTelemetryHandlerMappingFilter.doFilter(OpenTelemetryHandlerMappingFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:735)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by enggshashank** [comment]
Use this code, it worked for me.

WebDriverManager.chromedriver().clearDriverCache().setup();

**Comment by harithaSreejith** [comment]
@enggshashank,  Now the script is running without any issue after adding the above piece of code, Thanks

**Comment by Mithuzaw-US** [comment]
Hi team, I am having same issue, I updated to 5.7.0 version but not able to sync the webdrover manager, it's throwing error, need immediate assistant

**Comment by bkumar2018** [comment]
5.7.0 worked with below code

WebDriverManager.chromedriver().clearDriverCache().setup();

**Comment by Pooja-Shaw** [comment]
#NeedAssistance


Even on updating to 5.7.0 and replacing with below code , my issue is not resolved.

WebDriverManager.chromedriver().clearDriverCache().setup();

io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"

	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1445)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1461)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1442)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1435)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1205)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:427)
	at com.lowes.ProjectScheduling.Pages.Base.BaseTest.setupDriver(BaseTest.java:127)
	at com.lowes.ProjectScheduling.Pages.Base.BaseTest.beforeTest(BaseTest.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:661)
	at org.testng.TestRunner.beforeRun(TestRunner.java:650)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.NumberFormatException: For input string: "public"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:178)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:155)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1282)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1199)
	... 31 more
