### ISSUE TITLE
default-values all become null if configuration file exists

### ISSUE THREAD

**Issue by perchrh** [bonigarcia/webdrivermanager#261]
In a setup where everything works well (thanks), I want to lock the driver versions. 
I create a webdrivermanager.properties file with the following values:

wdm.chromeDriverVersion=2.42
wdm.internetExplorerVersion=3.14.0.12
wdm.operaDriverVersion=2.40
wdm.edgeDriverVersion=6.17134
wdm.phantomjsDriverVersion=2.1.0
wdm.geckoDriverVersion=0.23.0

When executing the tests now, there is an error inside webdrivermanager. The wdm.timeout is null. Defining wdm.timeout in the properties file removes the error, but now there is an error on aother config value, and testing reveals that every config value must be defined now in the properties file in order to avoid a crash. 

Please use default-values for properties that are not defined in webdrivermanager.propteries. 
This simplifies configuration and allows the updating of defaults without also updating the properties file.

**Comment by bonigarcia** [comment]
Thank you for your comments, @perchrh. I'll try to solve this issue by next version.

**Comment by bonigarcia** [comment]
Done.

**Comment by perchrh** [comment]
It still fails, the timeout has no value and an Exception is thrown.

**Comment by bonigarcia** [comment]
The problems seems you are using exactly the same name for your custom properties file than the used internally by WebDriverManager, i.e. `webdrivermanager.properties`. The solution would be renaming your properties (e.g. to `my-wdm.properties`) and then configure the manager as follows:

`WebDriverManager.chromedriver().properties("my-wdm.properties").setup();`
