### ISSUE TITLE
Giving proxy authentication error even when providing those details

### ISSUE THREAD

**Issue by anilreddy** [bonigarcia/webdrivermanager#518]
**Proxy Authentication Problem**: 
Even when providing the proxy details in the webdriver manager still am getting the proxy authentication issue. I have provided all the details below. Please let me know if you need more info.

**Browser and version**: 
Using the browser chrome and version is 84

**Operating system**: 
Using windows 10 latest version

**WebDriverManager version**: 
Using the latest version of webdrivermanager

**WebDriverManager use**: 

```java
WebDriverManager.chromedriver().proxy("http://proxysg.swg.apps.com:8080").proxyUser("apptester1").proxyPass("tester3").setup();
driver = new ChromeDriver();
```

**WebDriverManager traces**: 

```java
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Please answer the following questionnaire based on your experience with WebDriverManager. Thanks a lot!
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - ====> http://tiny.cc/wdm-survey <====
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 84.0.4147.30 (since Chrome 84 is installed in your machine)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] WARN org.apache.hc.client5.http.impl.classic.ConnectExec - Missing auth challenge
[main] WARN io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 84.0.4147.30 (org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required) ... trying again using latest driver stored in cache
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 84.0.4147.30 (since Chrome 84 is installed in your machine)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] WARN org.apache.hc.client5.http.impl.classic.ConnectExec - Missing auth challenge
[main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 84.0.4147.30 (org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required)
```

**Error trace**: 

```java
io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:839)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:97)
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:731)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:593)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:525)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:722)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:531)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:277)
	at com.uprr.selenide.train.consists.lib.DriverHelper.initializeDriver(DriverHelper.java:86)
	at com.uprr.selenide.train.consist.testdata.pages.LoginTest.setUpConfig(LoginTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:181)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89)
	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:137)
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:827)
	... 33 more
Caused by: org.apache.hc.client5.http.impl.TunnelRefusedException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required
	at org.apache.hc.client5.http.impl.classic.ConnectExec.createTunnelToTarget(ConnectExec.java:258)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:144)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:169)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	... 37 more
```

**Comment by bonigarcia** [comment]
From the log traces, I can see you are using WebDriverManager 4.0.0, which is not the latest version. Please update to WebDriverManager 4.1.0. There was a problem with the HttpClient 5 shipped with that version (see #508) which has been fixed in the next version of HttpClient 5, shipped with WebDriverManager 4.1.0. Maybe this solves your problem as well.

**Comment by anilreddy** [comment]
@bonigarcia I have updated WebDriverManager to 4.1.0 now issue is solved. Am closing this issue.

**Comment by du-it** [comment]
This problem still exists with WebDriverManager 5.1.1 and httpclient5 5.1.3. :
`WARN    Error reading commands.properties, using local instead
WARN    Error reading versions.properties, using local instead
INFO    Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
WARN    There was an error managing geckodriver (latest version) (CONNECT refused by proxy: HTTP/1.1 403 Forbidden) ... trying again using latest driver stored in cache
INFO    Reading https://api.github.com/repos/mozilla/geckodriver/releases to seek geckodriver
ERROR   There was an error managing geckodriver (latest version) (CONNECT refused by proxy: HTTP/1.1 403 Forbidden)
org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 403 Forbidden
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:173) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:89) ~[httpclient5-5.1.3.jar:5.1.3]
	at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:158) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:1483) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1497) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getDriverUrls(FirefoxDriverManager.java:102) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1327) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1165) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1083) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1322) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1299) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1089) ~[webdrivermanager-5.1.1.jar:?]
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:396) ~[webdrivermanager-5.1.1.jar:?]
	at com.tsystems.dap.inspector.session.modules.selenium.SeleniumModule.createClient(SeleniumModule.java:93) ~[classes/:?]
	at com.tsystems.dap.inspector.session.modules.selenium.SeleniumModule.init(SeleniumModule.java:112) ~[classes/:?]
	at com.tsystems.dap.inspector.session.modules.selenium.SeleniumModule.loginConsole(SeleniumModule.java:215) ~[classes/:?]
	at com.tsystems.dap.inspector.nodetree.creators.LibNodeCreator.lambda$loginAndOpenPage$101(LibNodeCreator.java:282) ~[classes/:?]
	at com.tsystems.dap.inspector.session.sessioncontroller.SessionController.executeSessionNodeSequenceWithThrow(SessionController.java:45) ~[classes/:?]
	at com.tsystems.dap.inspector.session.sessioncontroller.SessionController.executeSessionNodeSequence(SessionController.java:16) ~[classes/:?]
	at com.tsystems.dap.inspector.main.core.coremodules.SysTestRunnerModule.runSysTest(SysTestRunnerModule.java:122) ~[classes/:?]
	at com.tsystems.dap.inspector.main.core.coremodules.SysTestRunnerModule.runStandardSysTest(SysTestRunnerModule.java:35) ~[classes/:?]
	at com.tsystems.dap.inspector.main.inspectorserver.InspectorServerJsonProcessor.lambda$processCommand$0(InspectorServerJsonProcessor.java:133) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.hc.client5.http.impl.TunnelRefusedException: CONNECT refused by proxy: HTTP/1.1 403 Forbidden
	at org.apache.hc.client5.http.impl.classic.ConnectExec.createTunnelToTarget(ConnectExec.java:259) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:145) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170) ~[httpclient5-5.1.3.jar:5.1.3]
	... 23 more`

**Comment by bonigarcia** [comment]
@du-it This is a closed issue. Feel free to open a new one about it, but please, follow strictly the issue template to report all the required info, since otherwise it is impossible to debug it.
