### ISSUE TITLE
Upgrade to Chrome 96.0.4664.45 - incorrect driver loads

### ISSUE THREAD

**Issue by DarcheleWebb** [bonigarcia/webdrivermanager#747]
**Description of the problem**: 
     Chrome driver 94.0.4606.113 being downloaded instead of 96.0.4664.45 (all worked prior to Chrome upgrade)

**Browser and version**: 
    96.0.4664.45 - recently upgraded 

**Operating system**: 
    Windows Server 2019, 64-bit

**WebDriverManager version**:  
    Was using 4.4.0 got the error.  Tried to upgrade to 5.0.3 and still got the error.

**WebDriverManager call**: 
		WebDriverManager.chromedriver().setup()
		driver = {
			ChromeOptions options = new ChromeOptions();
			options.addArguments("start-maximized");
			new ChromeDriver(options);
		}

**WebDriverManager traces**: 
    10:52:25.976 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.VersionDetector - Detecting chrome version using online commands.properties
    10:52:25.983 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Running command on the shell: [cmd.exe, /C, wmic, datafile, where, name="%PROGRAMFILES(X86):\=\\%\\Google\\Chrome\\Application\\chrome.exe", get, Version, /value]
    10:52:26.356 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Result: 
    10:52:26.356 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Running command on the shell: [cmd.exe, /C, wmic, datafile, where, name="%LOCALAPPDATA:\=\\%\\Google\\Chrome\\Application\\chrome.exe", get, Version, /value]
    10:52:26.632 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Result: 
    10:52:26.633 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Running command on the shell: [cmd.exe, /C, wmic, datafile, where, name="%PROGRAMFILES:\=\\%\\Google\\Chrome\\Application\\chrome.exe", get, Version, /value]
    10:52:26.998 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Result: 
    10:52:26.999 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Running command on the shell: [REG, QUERY, HKCU\Software\Google\Chrome\BLBeacon, /v, version]
    10:52:27.115 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Result: HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon
        version    REG_SZ    94.0.4606.81
    10:52:27.117 [Test worker] DEBUG io.github.bonigarcia.wdm.cache.ResolutionCache - Resolution chrome94=94.0.4606.113 in cache (valid until 09:49:14 18/11/2021 CST)
    10:52:27.118 [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 94.0.4606.113 (resolved driver for Chrome 94)
    10:52:27.119 [Test worker] DEBUG io.github.bonigarcia.wdm.cache.ResolutionCache - Storing resolution chrome=94 in cache (valid until 11:52:27 17/11/2021 CST)
    10:52:27.144 [Test worker] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Driver chromedriver 94.0.4606.113 found in cache
    10:52:27.145 [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\SVC4CCSvaultAutoNPrd\.cache\selenium\chromedriver\win32\94.0.4606.113\chromedriver.exe
com.rgare.Central.CentralSpec > Central redirects to correct Secure Auth Realm STANDARD_ERROR
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 47184
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 53852
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 57450
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
com.rgare.Central.CentralSpec > Central redirects to correct Secure Auth Realm FAILED

**Error log**: None

**Comment by DarcheleWebb** [comment]
Some more details: 

 Caused by:
        org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 94
        Current browser version is 96.0.4664.45 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
        System info: host: 'STLSJENKINS01', ip: '10.17.116.192', os.name: 'Windows Server 2019', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_251'
        Driver info: driver.version: ChromeDriver
        remote stacktrace: Backtrace:
        	Ordinal0 [0x0132B3C3+2470851]
        	Ordinal0 [0x012C56A1+2053793]
        	Ordinal0 [0x011D2438+1057848]
        	Ordinal0 [0x011F054A+1181002]
        	Ordinal0 [0x011EC435+1164341]
        	Ordinal0 [0x011E9CAF+1154223]
        	Ordinal0 [0x01219ADF+1350367]
        	Ordinal0 [0x0121974A+1349450]
        	Ordinal0 [0x012155AB+1332651]
        	Ordinal0 [0x011F2104+1188100]
        	Ordinal0 [0x011F2F59+1191769]
        	GetHandleVerifier [0x014B1716+1549414]
        	GetHandleVerifier [0x0155C207+2248535]
        	GetHandleVerifier [0x013B676B+521403]
        	GetHandleVerifier [0x013B5809+517465]
        	Ordinal0 [0x012CA7DD+2074589]
        	Ordinal0 [0x012CEB98+2091928]
        	Ordinal0 [0x012CECD2+2092242]
        	Ordinal0 [0x012D8581+2131329]
        	BaseThreadInitThunk [0x77AA0419+25]
        	RtlGetAppContainerNamedObjectPath [0x77E172FD+237]
        	RtlGetAppContainerNamedObjectPath [0x77E172CD+189]

    geb.driver.DriverCreationException: failed to create driver from callback 'script16371679444022029770606$_run_closure1$_closure4$_closure9@3fbbe1'

**Comment by bonigarcia** [comment]
This problem probably is solved by now. WDM has a cache with a TTL (see [doc](https://bonigarcia.dev/webdrivermanager/#resolution-algorithm)), and when it expires, it downloads a fresh driver, which is supposed to be compliant with your Chrome 96. To force clearing the cache, simply execute this (once will be enough):

```
WebDriverManager.chromedriver().clearDriverCache().setup();
```

**Comment by DarcheleWebb** [comment]
Sorry... it is not resolved.  I deleted the entire cache and still have the issue.

:\Users\SVC4CCSvaultAutoNPrd\.cache\selenium\chromedriver\win32\94.0.4606.113\chromedriver.exe
com.rgare.Central.CentralSpec > Central redirects to correct Secure Auth Realm STANDARD_ERROR
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 26210
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 31956
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 27029
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
com.rgare.Central.CentralSpec > Central redirects to correct Secure Auth Realm FAILED
    geb.driver.DriverCreationException: failed to create driver from callback 'script16372438022412029770606$_run_closure1$_closure4$_closure9@3fbbe1'

        Caused by:
        org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 94
        Current browser version is 96.0.4664.45 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
        System info: host: 'STLSJENKINS01', ip: '10.17.116.192', os.name: 'Windows Server 2019', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_251'
        Driver info: driver.version: ChromeDriver
        remote stacktrace: Backtrace:
        	Ordinal0 [0x0061B3C3+2470851]
        	Ordinal0 [0x005B56A1+2053793]
        	Ordinal0 [0x004C2438+1057848]
        	Ordinal0 [0x004E054A+1181002]
        	Ordinal0 [0x004DC435+1164341]
        	Ordinal0 [0x004D9CAF+1154223]
        	Ordinal0 [0x00509ADF+1350367]
        	Ordinal0 [0x0050974A+1349450]
        	Ordinal0 [0x005055AB+1332651]
        	Ordinal0 [0x004E2104+1188100]
        	Ordinal0 [0x004E2F59+1191769]
        	GetHandleVerifier [0x007A1716+1549414]
        	GetHandleVerifier [0x0084C207+2248535]
        	GetHandleVerifier [0x006A676B+521403]
        	GetHandleVerifier [0x006A5809+517465]
        	Ordinal0 [0x005BA7DD+2074589]
        	Ordinal0 [0x005BEB98+2091928]
        	Ordinal0 [0x005BECD2+2092242]
        	Ordinal0 [0x005C8581+2131329]
        	BaseThreadInitThunk [0x77AA0419+25]
        	RtlGetAppContainerNamedObjectPath [0x77E172FD+237]
        	RtlGetAppContainerNamedObjectPath [0x77E172CD+189]

    geb.driver.DriverCreationException: failed to create driver from callback 'script16372438022412029770606$_run_closure1$_closure4$_closure9@3fbbe1'

**Comment by DarcheleWebb** [comment]
Double checked and deleted cache under user account as well.

08:33:44.850 [Test worker] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000003: releasing valid endpoint
    08:33:44.850 [Test worker] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000003: releasing endpoint
    08:33:44.850 [Test worker] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000003: connection http-outgoing-1 can be kept alive for 3 MINUTES
    08:33:44.850 [Test worker] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000003: connection released [route: {s}->https://chromedriver.storage.googleapis.com:443][total available: 2; route allocated: 1 of 5; total allocated: 2 of 25]
    08:33:44.890 [Test worker] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file chromedriver_win32.zip
    08:33:45.772 [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\SVC4CCSvaultAutoNPrd\.cache\selenium\chromedriver\win32\94.0.4606.113\chromedriver.exe

com.rgare.Central.CentralSpec > Central redirects to correct Secure Auth Realm STANDARD_ERROR
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 20938
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 36375
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.
    Starting ChromeDriver 94.0.4606.113 (9d935b6bb55ebbb1d06628ea2b6b0c812db527f4-refs/branch-heads/4606@{#1424}) on port 24166
    Only local connections are allowed.
    Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
    ChromeDriver was started successfully.

com.rgare.Central.CentralSpec > Central redirects to correct Secure Auth Realm FAILED
    geb.driver.DriverCreationException: failed to create driver from callback 'script16372460171602029770606$_run_closure1$_closure4$_closure9@f7f861'

        Caused by:
        org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 94
        Current browser version is 96.0.4664.45 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
        System info: host: 'STLSJENKINS01', ip: '10.17.116.192', os.name: 'Windows Server 2019', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_251'
        Driver info: driver.version: ChromeDriver

**Comment by bonigarcia** [comment]
From your first traces, it seems you have an inconsistency with the info in your registry, since the key `HKCU\Software\Google\Chrome\BLBeacon` says that you have Chrome 94, but then have installed Chrome 96:

```
10:52:26.999 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Running command on the shell: [REG, QUERY, HKCU\Software\Google\Chrome\BLBeacon, /v, version]
10:52:27.115 [Test worker] DEBUG io.github.bonigarcia.wdm.versions.Shell - Result: HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon
version REG_SZ 94.0.4606.81
```

**Comment by saumyaw** [comment]
I also faced the same issue after updating to the latest 96.0.4664.45 version.  @DarcheleWebb have you solved this issue?

This version of ChromeDriver only supports Chrome version 94
Current browser version is 96.0.4664.45 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe (SessionNotCreated)

**Comment by DarcheleWebb** [comment]
![image](https://user-images.githubusercontent.com/54723293/142872443-b151995b-971e-456d-88a2-fd6a63c1580d.png)

I checked the registry and the version appears correctly.

![image](https://user-images.githubusercontent.com/54723293/142872600-448de5e1-b843-445f-9842-ef31e01d2e09.png)

Any other thoughts?

**Comment by DarcheleWebb** [comment]
@saumyaw  Got it working.  I had to log into the build server with the build user and uninstall/reinstall Chrome and then delete the selenium cache before I got it working.
